version: "3.9"

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: process.env.USER 
      POSTGRES_PASSWORD: process.env.PASSWORD
      POSTGRES_DB: db1
    ports:
      - "5432:5432"